name: Test SSH Connection

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  IMAGE_TAG: latest
  CONTAINER_NAME: spring-api-gateway
  PORT: ${{ secrets.PORT }}
  CORS_ALLOWED_ORIGINS: ${{ secrets.CORS_ALLOWED_ORIGINS }}
  JWT_SECRET: ${{ secrets.JWT_SECRET }}
  USERS_MODULE_URL: ${{ secrets.USERS_MODULE_URL }}
  FACTURAS_MODULE_URL: ${{ secrets.FACTURAS_MODULE_URL }}
  REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
  REGISTRY_TOKEN: ${{ secrets.REGISTRY_TOKEN }}

on:
  workflow_run:
    workflows: ["Build and Push Image (Spring Boot Buildpacks)"]
    types: [completed]
    branches:
      - main
      - master
    workflow_dispatch:

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Test SSH Connection
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          envs: REGISTRY,IMAGE_NAME,IMAGE_TAG,CONTAINER_NAME,PORT,CORS_ALLOWED_ORIGINS,JWT_SECRET,USERS_MODULE_URL,FACTURAS_MODULE_URL,REGISTRY_USERNAME,REGISTRY_TOKEN
          script: echo "conexi√≥n exitosa"